clear
echo "=========================================================================="
echo "           { spCoinSimpleSwapTest } MAIN ALIAS MENU SETTINGS"
echo "=========================================================================="
echo "m = The main menu, it is a Menu of Menu's, It displays 'THIS' menu."
echo "pm = Project menu, stores project testing shourcut commands"
echo "em = Environment Menu, stores environment shortcut commands"
echo "tm = Testing Menu Alias, stores testing shortcut commands"
echo "um = User Menu Alias, used locally and not saved to remote git repository"
echo "=========================================================================="
